server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.csk3x5z6pzq3.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-nk?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r

  security:
    user:
      name: nk
      password: 1111

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  # 집
  path: C:/junil/ng/web/intellij/stussy-clone-20220929-ng/upload/
  # 학원
  #path: C:/Program Files/junil/web/springboot/stussy-clone-20220929-ng/upload/